# -*- coding: utf-8 -*-
"""Data_Preprocessing_for_ML_in_Python.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18t2yzjDRdZqt7Wc3ioOch5m2pnjPu7Hq

#Data Preprocessing for Machine learning in Python
• Pre-processing refers to the transformations applied to our data before feeding it to the algorithm.

• Data Preprocessing is a technique that is used to convert the raw data into a clean data set. In other words, whenever the data is gathered from different sources it is collected in raw format which is not feasible for the analysis.

![alt text](https://www.geeksforgeeks.org/wp-content/uploads/ml.png)
"""

data.head()
data.info()
data.describe(include="all")
data.dtypes

#Eliminar datos faltantes con dropna
# axis = 0: para eliminar las filas
# axis = 1: delete de collumns
data.drop('column_index', axis=1).reset_index(drop=True)

#replace
df['edad'].replace(np.nan, promedio)

#from categories to numbers
pd.get_dummies

# agrupacion de grupos
pd.cut